version: '3.8'

services:
  api:
    build: .
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - .:/kitworks-server
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - kitworks-postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379
    volumes:
      - kitworks-redis:/data

volumes:
  kitworks-postgres:
  kitworks-redis:
    driver: local
